# Form implementation generated from reading ui file 'homework.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(789, 652)
        self.stockTable = QtWidgets.QTableWidget(parent=Form)
        self.stockTable.setGeometry(QtCore.QRect(0, 0, 791, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockTable.sizePolicy().hasHeightForWidth())
        self.stockTable.setSizePolicy(sizePolicy)
        self.stockTable.setMouseTracking(True)
        self.stockTable.setAutoFillBackground(True)
        self.stockTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.stockTable.setDragEnabled(True)
        self.stockTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.stockTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.stockTable.setObjectName("stockTable")
        self.stockTable.setColumnCount(0)
        self.stockTable.setRowCount(0)
        self.stockTable.horizontalHeader().setVisible(True)
        self.stockTable.horizontalHeader().setCascadingSectionResizes(False)
        self.stockTable.verticalHeader().setVisible(True)
        self.stockTable.verticalHeader().setCascadingSectionResizes(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.stockTable.setSortingEnabled(True)
